<?php
class Constantes{
	const CADASTRADO_COM_SUCESSO = 1;
	const EDITADO_COM_SUCESSO = 2;
	const DELETADO_COM_SUCESSO = 3;
	
	const ERRO_DE_VALIDACAO = 1;
	const ERRO_DE_VALIDACAO_ARRAY = 2;
	const ERRO_DESCONHECIDO = 3;
	const ERRO_DESCONHECIDO_ARRAY = 4;
	const ERRO_ACESSO_NEGADO = 5;
}